services:
  nubank-training-recipe:
    build:
      context: ../../../
      dockerfile: Dockerfile
    image: nubank-training-recipe:${ENV_NAME}
    container_name: nubank-training-recipe-${ENV_NAME}
    restart: "no"
    env_file:
      - ../env/.env.${ENV_NAME}